const blogs = [
    {
        id: '1',
        title: 'Certified eJPT: Practical Skills in Penetration Testing and Network Security.',
        screens: 'images/blog/eJPT.jpg',
        description: 'Certified in eJPT (eLearnSecurity Penetration Tester), demonstrating practical skills in penetration testing, network security, and vulnerability assessment.',
        author: 'Abdullah Mahmoudi',
        
        create_at: '10 Sep, 2025',
        blogSingleImg:'images/blog/eJPT.jpg', 
        comment:'35',
        blClass:'format-standard-image',
    },
    {
        id: '2',
        title: ' Google Cybersecurity Certificate: Foundations and Best Practices.',
        screens: 'images/blog/google.jpg',
        description: 'Certified by Google in Cybersecurity, demonstrating knowledge of network security, threat analysis, and best practices in protecting digital systems.',
        author: 'Abdullah Mahmoudi',
        authorTitle:'Abdullah Mahmoudi',
        create_at: '13 Dec,2022',
        blogSingleImg:'images/blog/google.jpg', 
        comment:'80',
        blClass:'format-standard-image',
    },
    {
        id: '3',
        title: 'Advanced Cisco JavaScript Certificate: Expert Web Development Skills.',
        screens: 'images/blog/JS.jpg',
        description: 'Certified in JavaScript by CESCo, demonstrating proficiency in core concepts, DOM manipulation, ES6+ features, and practical web development skills.',
        author: 'Aliza Anny',
        authorTitle:'Abdullah Mahmoudi',
        create_at: '27 Dec,2024',
        blogSingleImg:'images/blog/js.jpg',
        comment:'95',
        blClass:'format-video',
    },
    {
        id: '4',
        title: 'Cisco Advanced Cybersecurity Certificate.',
        screens: 'images/blog/ci.jpg',
        description: 'Certified by Cisco in Advanced Cybersecurity, demonstrating expertise in network defense, threat detection, incident response, and securing enterprise systems.',
        author: 'Abdullah Mahmoudi',
        authorTitle:'Creative Director',
        create_at: '13 Dec,2022',
        blogSingleImg:'images/blog/ci.jpg', 
        comment:'80',
        blClass:'format-standard-image',
    },
];
export default blogs;